apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: new-go-app-0328 
  janus-idp.io/tekton: new-go-app-0328
  backstage.io/kubernetes-id: new-go-app-0328
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: new-go-app-0328
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  