apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: new-go-app-0328-gitops
  description: This is GitOps manifest for new-go-app-0328   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: new-go-app-0328
    janus-idp.io/tekton: new-go-app-0328 
    backstage.io/kubernetes-id: new-go-app-0328 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:new-go-app-0328
